use crate::model::Project;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GeneratedFile {
    pub path: String,
    pub contents: String,
}

pub fn generate_ratatui_project(project: &Project) -> Result<Vec<GeneratedFile>, String> {
    let project_json = serde_json::to_string_pretty(project).map_err(|error| error.to_string())?;
    let module_names: Vec<String> = project
        .frames
        .iter()
        .enumerate()
        .map(|(index, frame)| format!("screen_{index}_{}", rust_identifier(&frame.name)))
        .collect();
    let mut files = vec![
        file("Cargo.toml", cargo_toml(&rust_identifier(&project.name))),
        file(
            "README.md",
            format!(
                "# {}\n\nGenerated by TUI Builder.\n\n- Run with `cargo run`.\n- Switch screens with `Tab` / `Shift+Tab`.\n- Quit with `q` or `Esc`.\n\nThe generated scaffold is intentionally one-way; edit it as normal Rust code.\n",
                project.name
            ),
        ),
        file("src/design.json", project_json),
        file("src/main.rs", main_rs()),
        file("src/app.rs", app_rs(&module_names)),
        file(
            "src/screens/mod.rs",
            module_names
                .iter()
                .map(|name| format!("pub mod {name};\n"))
                .collect::<String>(),
        ),
        file("tui_builder_core/Cargo.toml", core_cargo_toml()),
        file(
            "tui_builder_core/src/lib.rs",
            "mod model;\nmod render;\npub use model::*;\npub use render::*;\n",
        ),
        file("tui_builder_core/src/model.rs", include_str!("model.rs")),
        file("tui_builder_core/src/render.rs", include_str!("render.rs")),
    ];
    for (frame, module) in project.frames.iter().zip(module_names.iter()) {
        files.push(file(format!("src/screens/{module}.rs"), format!(
            "use ratatui::{{buffer::Buffer, layout::Rect}};\nuse tui_builder_core::{{Project, render_frame_to_buffer}};\n\npub fn render(project: &Project, area: Rect, buffer: &mut Buffer) {{\n    render_frame_to_buffer(project, {:?}, area, buffer)\n        .expect(\"generated frame id must exist\");\n}}\n",
            frame.id
        )));
    }
    Ok(files)
}

fn file(path: impl Into<String>, contents: impl Into<String>) -> GeneratedFile {
    GeneratedFile {
        path: path.into(),
        contents: contents.into(),
    }
}
fn rust_identifier(value: &str) -> String {
    let mut result = String::new();
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            result.push(character.to_ascii_lowercase());
        } else if !result.ends_with('_') {
            result.push('_');
        }
    }
    let result = result.trim_matches('_');
    let mut result = if result.is_empty() {
        "tui_app".to_owned()
    } else {
        result.to_owned()
    };
    if result.starts_with(|c: char| c.is_ascii_digit()) {
        result.insert(0, '_');
    }
    result
}

fn cargo_toml(name: &str) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.2"
serde_json = "1"
tui-builder-core = {{ path = "tui_builder_core" }}
"#
    )
}
fn core_cargo_toml() -> String {
    r#"[package]
name = "tui-builder-core"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.30.2", default-features = false, features = ["widget-calendar", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = { version = "0.3", default-features = false }
"#
    .into()
}

fn main_rs() -> String {
    r#"mod app;
mod screens;

use app::App;
use ratatui::crossterm::event::{self, Event, KeyCode, KeyEventKind, KeyModifiers};
use std::io;

fn main() -> io::Result<()> {
    let mut terminal = ratatui::init();
    let result = run(&mut terminal);
    ratatui::restore();
    result
}

fn run(terminal: &mut ratatui::DefaultTerminal) -> io::Result<()> {
    let mut app = App::new();
    loop {
        terminal.draw(|frame| app.render(frame))?;
        if let Event::Key(key) = event::read()? {
            if key.kind != KeyEventKind::Press {
                continue;
            }
            match key.code {
                KeyCode::Char('q') | KeyCode::Esc => return Ok(()),
                KeyCode::Tab if key.modifiers.contains(KeyModifiers::SHIFT) => app.previous(),
                KeyCode::BackTab => app.previous(),
                KeyCode::Tab => app.next(),
                _ => {}
            }
        }
    }
}
"#
    .into()
}

fn app_rs(modules: &[String]) -> String {
    let variants = modules
        .iter()
        .enumerate()
        .map(|(index, module)| {
            format!(
                "            {index} => screens::{module}::render(&self.project, area, buffer),"
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"use crate::screens;
use ratatui::Frame;
use tui_builder_core::Project;

pub struct App {{
    project: Project,
    screen: usize,
}}

impl App {{
    pub fn new() -> Self {{
        let project = serde_json::from_str(include_str!("design.json"))
            .expect("embedded design must be valid");
        Self {{ project, screen: 0 }}
    }}

    pub fn next(&mut self) {{
        self.screen = (self.screen + 1) % self.project.frames.len().max(1);
    }}
    pub fn previous(&mut self) {{
        self.screen = (self.screen + self.project.frames.len().saturating_sub(1))
            % self.project.frames.len().max(1);
    }}

    pub fn render(&self, frame: &mut Frame) {{
        let area = frame.area();
        let buffer = frame.buffer_mut();
        match self.screen {{
{variants}
            _ => {{}}
        }}
    }}
}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn identifier_is_safe() {
        assert_eq!(rust_identifier("My TUI!"), "my_tui");
        assert_eq!(rust_identifier("42"), "_42");
    }
}
