import { Copy, Frame, LayoutPanelTop, RotateCcw, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { defaultBlock, named } from "../sample";
import { getSelectedFrame, getSelectedNode, useBuilder } from "../store";
import { findNodeParent, type CellStyle, type Constraint, type Node, type WidgetNode } from "../types";

function NumberInput({ value, onChange, min, max, step }: { value: number; onChange: (value: number) => void; min?: number; max?: number; step?: number }) { return <input type="number" value={value} min={min} max={max} step={step} onChange={(event) => onChange(Number(event.target.value))} />; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function Section({ title, children, defaultOpen = true }: { title: string; children: React.ReactNode; defaultOpen?: boolean }) { return <details className="inspector-section" open={defaultOpen}><summary>{title}</summary><div>{children}</div></details>; }

const namedColors = ["white", "gray", "darkGray", "black", "red", "lightRed", "green", "lightGreen", "yellow", "lightYellow", "blue", "lightBlue", "magenta", "lightMagenta", "cyan", "lightCyan"] as const;
function StyleEditor({ value, update }: { value: CellStyle; update: (style: CellStyle) => void }) {
  const fg = value.foreground?.kind === "named" ? value.foreground.value : "white"; const bg = value.background?.kind === "named" ? value.background.value : "black";
  return <><div className="two-columns"><Field label="Foreground"><select value={fg} onChange={(event) => update({ ...value, foreground: named(event.target.value as never) })}>{namedColors.map((color) => <option key={color}>{color}</option>)}</select></Field><Field label="Background"><select value={bg} onChange={(event) => update({ ...value, background: named(event.target.value as never) })}>{namedColors.map((color) => <option key={color}>{color}</option>)}</select></Field></div><div className="toggle-row">{(["bold", "dim", "italic", "underlined", "reversed"] as const).map((key) => <button key={key} className={value[key] ? "active" : ""} onClick={() => update({ ...value, [key]: !value[key] })}>{key === "underlined" ? "U" : key[0].toUpperCase()}</button>)}</div></>;
}

function ConstraintEditor({ value, update }: { value: Constraint; update: (value: Constraint) => void }) {
  const numeric = value.kind === "ratio" ? value.value[0] : value.value;
  return <div className="constraint-editor"><select value={value.kind} onChange={(event) => update(event.target.value === "ratio" ? { kind: "ratio", value: [1, 2] } : { kind: event.target.value as Exclude<Constraint["kind"], "ratio">, value: 1 })}><option value="fill">Fill</option><option value="length">Fixed cells</option><option value="percentage">Percent</option><option value="min">Minimum</option><option value="max">Maximum</option><option value="ratio">Ratio</option></select><NumberInput value={numeric} min={0} onChange={(number) => update(value.kind === "ratio" ? { ...value, value: [number, value.value[1]] } : { ...value, value: number } as Constraint)} />{value.kind === "ratio" && <><span>:</span><NumberInput value={value.value[1]} min={1} onChange={(number) => update({ ...value, value: [value.value[0], Math.max(1, number)] })} /></>}</div>;
}

function WidgetFields({ node, update }: { node: WidgetNode; update: (mutate: (node: WidgetNode) => void) => void }) {
  const widget = node.widget;
  const patch = (value: Partial<typeof widget>) => update((target) => { target.widget = { ...target.widget, ...value } as typeof target.widget; });
  if (widget.kind === "paragraph") return <><Field label="Content"><textarea rows={6} value={widget.text} onChange={(event) => patch({ text: event.target.value })} /></Field><div className="two-columns"><Field label="Align"><select value={widget.alignment} onChange={(event) => patch({ alignment: event.target.value as typeof widget.alignment })}><option>left</option><option>center</option><option>right</option></select></Field><Field label="Wrap"><input type="checkbox" checked={widget.wrap} onChange={(event) => patch({ wrap: event.target.checked })} /></Field></div></>;
  if (widget.kind === "list") return <><Field label="Items"><textarea rows={6} value={widget.items.join("\n")} onChange={(event) => patch({ items: event.target.value.split("\n") })} /></Field><Field label="Selected row"><NumberInput value={widget.selected ?? 0} min={0} onChange={(selected) => patch({ selected })} /></Field></>;
  if (widget.kind === "tabs") return <><Field label="Labels"><textarea rows={3} value={widget.labels.join("\n")} onChange={(event) => patch({ labels: event.target.value.split("\n") })} /></Field><Field label="Selected tab"><NumberInput value={widget.selected} min={0} onChange={(selected) => patch({ selected })} /></Field></>;
  if (widget.kind === "table") return <><Field label="Headers"><input value={widget.headers.join(", ")} onChange={(event) => patch({ headers: event.target.value.split(",").map((value) => value.trim()) })} /></Field><Field label="Rows"><textarea rows={7} value={widget.rows.map((row) => row.join(", ")).join("\n")} onChange={(event) => patch({ rows: event.target.value.split("\n").map((row) => row.split(",").map((value) => value.trim())) })} /></Field><Field label="Selected row"><NumberInput value={widget.selected ?? 0} min={0} onChange={(selected) => patch({ selected })} /></Field></>;
  if (widget.kind === "barChart") return <><Field label="Bars"><textarea rows={7} value={widget.bars.map((bar) => `${bar.label}, ${bar.value}`).join("\n")} onChange={(event) => patch({ bars: event.target.value.split("\n").map((row) => { const [label, value] = row.split(","); return { label: label?.trim() ?? "", value: Number(value) || 0 }; }) })} /></Field><div className="two-columns"><Field label="Bar width"><NumberInput value={widget.barWidth} min={1} onChange={(barWidth) => patch({ barWidth })} /></Field><Field label="Gap"><NumberInput value={widget.gap} min={0} onChange={(gap) => patch({ gap })} /></Field></div></>;
  if (widget.kind === "sparkline") return <Field label="Values"><textarea rows={5} value={widget.data.join(", ")} onChange={(event) => patch({ data: event.target.value.split(",").map((value) => Number(value.trim()) || 0) })} /></Field>;
  if (widget.kind === "gauge" || widget.kind === "lineGauge") return <><Field label="Label"><input value={widget.label} onChange={(event) => patch({ label: event.target.value })} /></Field><Field label="Value"><div className="range-field"><input type="range" min="0" max="1" step="0.01" value={widget.ratio} onChange={(event) => patch({ ratio: Number(event.target.value) })} /><span>{Math.round(widget.ratio * 100)}%</span></div></Field></>;
  if (widget.kind === "calendar") return <div className="three-columns"><Field label="Year"><NumberInput value={widget.year} onChange={(year) => patch({ year })} /></Field><Field label="Month"><NumberInput value={widget.month} min={1} max={12} onChange={(month) => patch({ month })} /></Field><Field label="Day"><NumberInput value={widget.selectedDay ?? 1} min={1} max={31} onChange={(selectedDay) => patch({ selectedDay })} /></Field></div>;
  if (widget.kind === "fill") return <Field label="Symbol"><input maxLength={2} value={widget.symbol} onChange={(event) => patch({ symbol: event.target.value })} /></Field>;
  if (widget.kind === "scrollbar") return <><div className="two-columns"><Field label="Length"><NumberInput value={widget.contentLength} min={1} onChange={(contentLength) => patch({ contentLength })} /></Field><Field label="Position"><NumberInput value={widget.position} min={0} onChange={(position) => patch({ position })} /></Field></div><Field label="Orientation"><select value={widget.orientation} onChange={(event) => patch({ orientation: event.target.value as typeof widget.orientation })}><option value="verticalRight">Right</option><option value="verticalLeft">Left</option><option value="horizontalTop">Top</option><option value="horizontalBottom">Bottom</option></select></Field></>;
  if (widget.kind === "canvas") return <CanvasEditor node={node as WidgetNode & { widget: typeof widget }} update={update} />;
  return <StructuredData node={node} update={update} />;
}

function CanvasEditor({ node, update }: { node: WidgetNode & { widget: Extract<WidgetNode["widget"], { kind: "canvas" }> }; update: (mutate: (node: WidgetNode) => void) => void }) {
  const [selected, setSelected] = useState(0); const shape = node.widget.shapes[selected]; const [source, setSource] = useState(shape ? JSON.stringify(shape, null, 2) : "");
  useEffect(() => setSource(shape ? JSON.stringify(shape, null, 2) : ""), [shape]);
  const mutateCanvas = (mutate: (widget: Extract<WidgetNode["widget"], { kind: "canvas" }>) => void) => update((target) => { if (target.widget.kind === "canvas") mutate(target.widget); });
  const addShape = () => { mutateCanvas((widget) => widget.shapes.push({ kind: "line", x1: 10, y1: 10, x2: 90, y2: 90 })); setSelected(node.widget.shapes.length); };
  const apply = () => { try { const next = JSON.parse(source); mutateCanvas((widget) => { widget.shapes[selected] = next; }); } catch { /* Keep the draft available for correction. */ } };
  return <><div className="two-columns"><Field label="X bounds"><input value={node.widget.xBounds.join(", ")} onChange={(event) => mutateCanvas((widget) => { widget.xBounds = event.target.value.split(",").map(Number).slice(0, 2) as [number, number]; })} /></Field><Field label="Y bounds"><input value={node.widget.yBounds.join(", ")} onChange={(event) => mutateCanvas((widget) => { widget.yBounds = event.target.value.split(",").map(Number).slice(0, 2) as [number, number]; })} /></Field></div><div className="shape-list">{node.widget.shapes.map((item, index) => <button key={index} className={selected === index ? "active" : ""} onClick={() => setSelected(index)}><span>{index + 1}</span>{item.kind}</button>)}<button onClick={addShape}>+ shape</button></div>{shape && <><Field label="Shape"><textarea className="code-input" rows={9} value={source} onChange={(event) => setSource(event.target.value)} /></Field><div className="shape-actions"><button onClick={apply}>Apply shape</button><button onClick={() => { mutateCanvas((widget) => widget.shapes.splice(selected, 1)); setSelected(Math.max(0, selected - 1)); }}>Remove</button></div></>}</>;
}

function StructuredData({ node, update }: { node: WidgetNode; update: (mutate: (node: WidgetNode) => void) => void }) {
  const [source, setSource] = useState(JSON.stringify(node.widget, null, 2)); const [error, setError] = useState<string>();
  useEffect(() => setSource(JSON.stringify(node.widget, null, 2)), [node.id, node.widget]);
  const apply = () => { try { const widget = JSON.parse(source); if (widget.kind !== node.widget.kind) throw new Error("Widget kind cannot change here"); update((target) => { target.widget = widget; }); setError(undefined); } catch (reason) { setError(reason instanceof Error ? reason.message : "Invalid JSON"); } };
  return <><Field label="Sample data"><textarea className="code-input" rows={12} value={source} onChange={(event) => setSource(event.target.value)} /></Field>{error && <p className="field-error">{error}</p>}<button className="button inspector-apply" onClick={apply}>Apply data</button></>;
}

export function Inspector() {
  const frame = useBuilder(getSelectedFrame); const node = useBuilder(getSelectedNode); const updateFrame = useBuilder((state) => state.updateFrame); const updateNode = useBuilder((state) => state.updateNode); const removeNode = useBuilder((state) => state.removeNode); const duplicateNode = useBuilder((state) => state.duplicateNode); const duplicateFrame = useBuilder((state) => state.duplicateFrame); const removeFrame = useBuilder((state) => state.removeFrame); const project = useBuilder((state) => state.project);
  if (!frame) return <aside className="inspector right-panel"><div className="inspector-empty"><Frame size={24} /><strong>No frame selected</strong><span>Select or create a frame.</span></div></aside>;
  const mutateNode = (mutate: (target: Node) => void) => node && updateNode(node.id, mutate);
  const parent = node ? findNodeParent(frame.root, node.id) ?? frame.overlays.map((overlay) => findNodeParent(overlay.root, node.id)).find(Boolean) : undefined; const child = parent?.children.find((entry) => entry.node.id === node?.id);
  const overlay = node ? frame.overlays.find((item) => !!findNodeParent(item.root, node.id) || item.root.id === node.id) : undefined;
  const updateOverlay = (patch: Partial<NonNullable<typeof overlay>>) => { if (!overlay) return; updateFrame(frame.id, { overlays: frame.overlays.map((item) => item.id === overlay.id ? { ...item, ...patch } : item) }); };
  return <aside className="inspector right-panel"><div className="inspector-title"><span>{node ? <LayoutPanelTop size={14} /> : <Frame size={14} />}{node ? "Layer" : "Frame"}</span><div>{node && <><button title="Duplicate" onClick={() => duplicateNode(node.id)}><Copy size={13} /></button>{node.id !== frame.root.id && <button title="Delete" onClick={() => removeNode(node.id)}><Trash2 size={13} /></button>}</>}</div></div>
    {!node ? <>
      <Section title="Frame"><Field label="Name"><input value={frame.name} onChange={(event) => updateFrame(frame.id, { name: event.target.value })} /></Field><div className="two-columns"><Field label="Columns"><NumberInput value={frame.columns} min={20} max={300} onChange={(columns) => updateFrame(frame.id, { columns })} /></Field><Field label="Rows"><NumberInput value={frame.rows} min={8} max={120} onChange={(rows) => updateFrame(frame.id, { rows })} /></Field></div><div className="two-columns"><Field label="X"><NumberInput value={frame.x} onChange={(x) => updateFrame(frame.id, { x })} /></Field><Field label="Y"><NumberInput value={frame.y} onChange={(y) => updateFrame(frame.id, { y })} /></Field></div></Section>
      <div className="inspector-actions"><button onClick={() => duplicateFrame(frame.id)}><Copy size={13} /> Duplicate</button>{project.frames.length > 1 && <button className="danger" onClick={() => removeFrame(frame.id)}><Trash2 size={13} /> Delete frame</button>}</div>
    </> : <>
      <Section title="Layer"><Field label="Name"><input value={node.name} onChange={(event) => mutateNode((target) => { target.name = event.target.value; })} /></Field>{child && <Field label="Size"><ConstraintEditor value={child.constraint} update={(constraint) => updateNode(parent!.id, (target) => { if (target.type === "layout") { const found = target.children.find((item) => item.node.id === node.id); if (found) found.constraint = constraint; } })} /></Field>}</Section>
      {overlay && <Section title="Overlay"><Field label="Name"><input value={overlay.name} onChange={(event) => updateOverlay({ name: event.target.value })} /></Field><Field label="Anchor"><select value={overlay.anchor} onChange={(event) => updateOverlay({ anchor: event.target.value as typeof overlay.anchor })}><option value="topLeft">Top left</option><option value="top">Top</option><option value="topRight">Top right</option><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option><option value="bottomLeft">Bottom left</option><option value="bottom">Bottom</option><option value="bottomRight">Bottom right</option></select></Field><Field label="Width"><ConstraintEditor value={overlay.width} update={(width) => updateOverlay({ width })} /></Field><Field label="Height"><ConstraintEditor value={overlay.height} update={(height) => updateOverlay({ height })} /></Field></Section>}
      {node.type === "layout" ? <Section title="Layout"><div className="two-columns"><Field label="Direction"><select value={node.direction} onChange={(event) => mutateNode((target) => { if (target.type === "layout") target.direction = event.target.value as typeof target.direction; })}><option value="horizontal">Row</option><option value="vertical">Column</option></select></Field><Field label="Spacing"><NumberInput value={node.spacing} min={0} onChange={(spacing) => mutateNode((target) => { if (target.type === "layout") target.spacing = spacing; })} /></Field></div><div className="two-columns"><Field label="Margin"><NumberInput value={node.margin} min={0} onChange={(margin) => mutateNode((target) => { if (target.type === "layout") target.margin = margin; })} /></Field><Field label="Distribute"><select value={node.flex} onChange={(event) => mutateNode((target) => { if (target.type === "layout") target.flex = event.target.value as typeof target.flex; })}><option value="legacy">Fill</option><option value="start">Start</option><option value="center">Center</option><option value="end">End</option><option value="spaceBetween">Space between</option><option value="spaceAround">Space around</option><option value="spaceEvenly">Space evenly</option></select></Field></div></Section> : <>
        <Section title={node.widget.kind}><WidgetFields node={node} update={(mutate) => updateNode(node.id, (target) => { if (target.type === "widget") mutate(target); })} /></Section>
        <Section title="Appearance"><StyleEditor value={node.style} update={(style) => mutateNode((target) => { if (target.type === "widget") target.style = style; })} /></Section>
        <Section title="Container"><label className="switch-field"><span>Block</span><input type="checkbox" checked={!!node.block} onChange={(event) => mutateNode((target) => { if (target.type === "widget") target.block = event.target.checked ? defaultBlock(target.name.toUpperCase()) : undefined; })} /></label>{node.block && <><Field label="Title"><input value={node.block.title} onChange={(event) => mutateNode((target) => { if (target.type === "widget" && target.block) target.block.title = event.target.value; })} /></Field><div className="two-columns"><Field label="Border"><select value={node.block.borderType} onChange={(event) => mutateNode((target) => { if (target.type === "widget" && target.block) target.block.borderType = event.target.value as typeof target.block.borderType; })}><option>plain</option><option>rounded</option><option>double</option><option>thick</option><option value="quadrantInside">quadrant inside</option><option value="quadrantOutside">quadrant outside</option></select></Field><Field label="Shadow"><input type="checkbox" checked={node.block.shadow} onChange={(event) => mutateNode((target) => { if (target.type === "widget" && target.block) target.block.shadow = event.target.checked; })} /></Field></div></>}</Section>
      </>}
      <div className="inspector-actions"><button onClick={() => duplicateNode(node.id)}><Copy size={13} /> Duplicate</button>{node.id !== frame.root.id && <button className="danger" onClick={() => removeNode(node.id)}><Trash2 size={13} /> Delete</button>}<button onClick={() => mutateNode(() => {})}><RotateCcw size={13} /> Refresh</button></div>
    </>}
  </aside>;
}
